version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_URL_GAMI=${NEXT_PUBLIC_URL_GAMI}
      - NEXT_PUBLIC_API_TOKEN=${NEXT_PUBLIC_API_TOKEN}
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  # Opcional: para desenvolvimento
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped